<?php
/**
 * Created by PhpStorm.
 * User: rocky
 * Date: 2021-01-01
 * Time: 09:45
 */

namespace Eadmin\component\form\field;


use Eadmin\component\form\Field;

/**
 * Class FormItem
 * @package Eadmin\component\form\field
 * @method $this size(string $value) 尺寸 medium / small / mini
 * @method $this prop(string $value) 表单域 model 字段
 * @method $this label(string $value) 标签文本
 * @method $this labelWidth(string $value) 表单域标签的的宽度，例如 '50px'。支持 auto
 * @method $this required(bool $value) 是否必填
 * @method $this rules(array $value) 表单验证规则
 * @method $this error(string $value) 表单域验证错误信息, 设置该值会使表单验证状态变为error，并显示该错误信息
 * @method $this showMessage(bool $value) 是否显示校验错误信息
 * @method $this inlineMessage(bool $value) 以行内形式展示校验信息
 */
class FormItem extends Field
{
    protected $name = 'ElFormItem';

    //表单数据对象字段
    protected $modelField = '';

    public function __construct($prop, $label)
    {
        $this->prop($prop);
        $this->label($label);
    }

    public function item($content)
    {
        if ($content instanceof Field && $this->modelField) {
            $modelField = $content->attr('modelField');
            $content->attr('modelField', $this->modelField . '.' . $modelField);
        }
        return $this->content($content); // TODO: Change the autogenerated stub
    }

    /**
     * 设置form 表单数据对象字段
     * @param string $field
     * @return $this
     */
    public function modelField($field)
    {
        $this->modelField = $field;
        return $this;
    }

    /**
     * 创建输入框
     * @param string $prop 表单域 model 字段
     * @param string $label 标签文本
     * @return static
     */
    public static function create($prop = '', $label = '')
    {
        return new static($prop, $label);
    }
}