<?php
/**
 * Created by PhpStorm.
 * User: rocky
 * Date: 2021-02-09
 * Time: 10:48
 */

namespace Eadmin\component\form\field;


use Eadmin\component\form\FormItem;

class Mobile extends Input
{
    public function setFormItem(FormItem $formItem)
    {
        parent::setFormItem($formItem); // TODO: Change the autogenerated stub
        $this->rule(['mobile' => '请输入正确的手机号']);
    }
}