<?php


namespace Eadmin\component\basic;


use Eadmin\component\Component;
use Eadmin\traits\CallProvide;

/**
 * Class FileSystem
 * @package Eadmin\component\basic
 * @method $this initPath(string $path) 目录路径
 * @method $this data(array $data) 数据
 */
class FileSystem extends Component
{
    use CallProvide;
    protected $name = 'EadminFileSystem';
    public function __construct($data)
    {
        $this->data($data);
        $this->getCallMethod();
        $this->attr('params',$this->getCallMethod());
        $this->attr('tools',[
           Button::create('新建文件夹')
               ->sizeMini()->confirm('文件夹名称','')->title('')->input()
        ]);
    }

    public function jsonSerialize()
    {
        if (request()->has('ajax_request_data')) {
            return ['code' => 200, 'data' => $this->attr('data')];
        }
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
}
