<?php


namespace Eadmin\component\basic;


use Eadmin\component\Component;
use Eadmin\component\form\field\Upload;
use Eadmin\traits\CallProvide;

/**
 * Class FileSystem
 * @package Eadmin\component\basic
 * @method $this initPath(string $path) 目录路径
 * @method $this data(array $data) 数据
 */
class FileSystem extends Component
{
    use CallProvide;
    protected $name = 'EadminFileSystem';

    public function __construct($data)
    {
        $this->data($data);
        $this->getCallMethod();
        $this->attr('params', $this->getCallMethod());
        $this->attr('upload',Upload::create()->attr('foreverShow',true)->content(
            Button::create('上传')
                ->sizeMini()
        ));
    }

    public function jsonSerialize()
    {
        if (request()->has('ajax_request_data')) {
            return ['code' => 200, 'data' => $this->attr('data')];
        }
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
}
